apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::339712988423:role/eksctl-eks-devops-cluster-nodegrou-NodeInstanceRole-RVxAIguZgnWD
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::339712988423:role/Jenkins-EC2-Role
      username: jenkins
      groups:
        - system:masters